export const REQUEST_POST_PENDING = "REQUEST_POST_PENDING";
export const REQUEST_POST_SUCCESS = "REQUEST_POST_SUCCESS";
export const REQUEST_POST_FAILED = "REQUEST_POST_FAILED";

export const REQUEST_CREATE_POST_PENDING = "REQUEST_CREATE_POST_PENDING";
export const REQUEST_CREATE_POST_SUCCESS = "REQUEST_CREATE_POST_SUCCESS";
export const REQUEST_CREATE_POST_FAILED = "REQUEST_CREATE_POST_FAILED";

export const REQUEST_EDIT_POST_PENDING = "REQUEST_EDIT_POST_PENDING";
export const REQUEST_EDIT_POST_SUCCESS = "REQUEST_EDIT_POST_SUCCESS";
export const REQUEST_EDIT_POST_FAILED = "REQUEST_EDIT_POST_FAILED";

export const REQUEST_POST_DETAILS_PENDING = "REQUEST_POST_DETAILS_PENDING";
export const REQUEST_POST_DETAILS_SUCCESS = "REQUEST_POST_DETAILS_SUCCESS";
export const REQUEST_POST_DETAILS_FAILED = "REQUEST_POST_DETAILS_FAILED";